<?php
/**
 * ProfilePrivacySettings
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Verdigado\GrueneApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gruene API
 *
 * ## OpenAPI Endpoints <a href=\"/api-json\">OpenAPI Spec in JSON</a><br> <a href=\"/api-yaml\">OpenAPI Spec in YAML</a><br>  ### Offboarding Every service conntected to Grünes Netz needs to remove users when they are removed from `saml.gruene.de`. Connected services need to pull a list of users waiting for removal at least once a week. api.gruene.de needs to be informed whether the user did not exist or was removed. API tokens can be obtained from `technik@verdigado.com`.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Verdigado\GrueneApiClient\models;

use \ArrayAccess;
use \Verdigado\GrueneApiClient\ObjectSerializer;

/**
 * ProfilePrivacySettings Class Doc Comment
 *
 * @category Class
 * @package  Verdigado\GrueneApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProfilePrivacySettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProfilePrivacySettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'overall' => 'string',
        'email' => 'string',
        'chatbegruenung' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'overall' => null,
        'email' => null,
        'chatbegruenung' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'overall' => false,
		'email' => false,
		'chatbegruenung' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'overall' => 'overall',
        'email' => 'email',
        'chatbegruenung' => 'chatbegruenung'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'overall' => 'setOverall',
        'email' => 'setEmail',
        'chatbegruenung' => 'setChatbegruenung'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'overall' => 'getOverall',
        'email' => 'getEmail',
        'chatbegruenung' => 'getChatbegruenung'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const OVERALL__PRIVATE = 'PRIVATE';
    public const OVERALL__PUBLIC = 'PUBLIC';
    public const OVERALL_BV_WIDE = 'BV_WIDE';
    public const OVERALL_LV_WIDE = 'LV_WIDE';
    public const OVERALL_KV_WIDE = 'KV_WIDE';
    public const OVERALL_OV_WIDE = 'OV_WIDE';
    public const EMAIL__PRIVATE = 'PRIVATE';
    public const EMAIL__PUBLIC = 'PUBLIC';
    public const EMAIL_BV_WIDE = 'BV_WIDE';
    public const EMAIL_LV_WIDE = 'LV_WIDE';
    public const EMAIL_KV_WIDE = 'KV_WIDE';
    public const EMAIL_OV_WIDE = 'OV_WIDE';
    public const CHATBEGRUENUNG__PRIVATE = 'PRIVATE';
    public const CHATBEGRUENUNG__PUBLIC = 'PUBLIC';
    public const CHATBEGRUENUNG_BV_WIDE = 'BV_WIDE';
    public const CHATBEGRUENUNG_LV_WIDE = 'LV_WIDE';
    public const CHATBEGRUENUNG_KV_WIDE = 'KV_WIDE';
    public const CHATBEGRUENUNG_OV_WIDE = 'OV_WIDE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOverallAllowableValues()
    {
        return [
            self::OVERALL__PRIVATE,
            self::OVERALL__PUBLIC,
            self::OVERALL_BV_WIDE,
            self::OVERALL_LV_WIDE,
            self::OVERALL_KV_WIDE,
            self::OVERALL_OV_WIDE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEmailAllowableValues()
    {
        return [
            self::EMAIL__PRIVATE,
            self::EMAIL__PUBLIC,
            self::EMAIL_BV_WIDE,
            self::EMAIL_LV_WIDE,
            self::EMAIL_KV_WIDE,
            self::EMAIL_OV_WIDE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChatbegruenungAllowableValues()
    {
        return [
            self::CHATBEGRUENUNG__PRIVATE,
            self::CHATBEGRUENUNG__PUBLIC,
            self::CHATBEGRUENUNG_BV_WIDE,
            self::CHATBEGRUENUNG_LV_WIDE,
            self::CHATBEGRUENUNG_KV_WIDE,
            self::CHATBEGRUENUNG_OV_WIDE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('overall', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('chatbegruenung', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['overall'] === null) {
            $invalidProperties[] = "'overall' can't be null";
        }
        $allowedValues = $this->getOverallAllowableValues();
        if (!is_null($this->container['overall']) && !in_array($this->container['overall'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'overall', must be one of '%s'",
                $this->container['overall'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        $allowedValues = $this->getEmailAllowableValues();
        if (!is_null($this->container['email']) && !in_array($this->container['email'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'email', must be one of '%s'",
                $this->container['email'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['chatbegruenung'] === null) {
            $invalidProperties[] = "'chatbegruenung' can't be null";
        }
        $allowedValues = $this->getChatbegruenungAllowableValues();
        if (!is_null($this->container['chatbegruenung']) && !in_array($this->container['chatbegruenung'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'chatbegruenung', must be one of '%s'",
                $this->container['chatbegruenung'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets overall
     *
     * @return string
     */
    public function getOverall()
    {
        return $this->container['overall'];
    }

    /**
     * Sets overall
     *
     * @param string $overall overall
     *
     * @return self
     */
    public function setOverall($overall)
    {
        if (is_null($overall)) {
            throw new \InvalidArgumentException('non-nullable overall cannot be null');
        }
        $allowedValues = $this->getOverallAllowableValues();
        if (!in_array($overall, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'overall', must be one of '%s'",
                    $overall,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['overall'] = $overall;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $allowedValues = $this->getEmailAllowableValues();
        if (!in_array($email, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'email', must be one of '%s'",
                    $email,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets chatbegruenung
     *
     * @return string
     */
    public function getChatbegruenung()
    {
        return $this->container['chatbegruenung'];
    }

    /**
     * Sets chatbegruenung
     *
     * @param string $chatbegruenung chatbegruenung
     *
     * @return self
     */
    public function setChatbegruenung($chatbegruenung)
    {
        if (is_null($chatbegruenung)) {
            throw new \InvalidArgumentException('non-nullable chatbegruenung cannot be null');
        }
        $allowedValues = $this->getChatbegruenungAllowableValues();
        if (!in_array($chatbegruenung, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'chatbegruenung', must be one of '%s'",
                    $chatbegruenung,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['chatbegruenung'] = $chatbegruenung;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


