<?php
/**
 * DivisionsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Verdigado\GrueneApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gruene API
 *
 * ## OpenAPI Endpoints <a href=\"/api-json\">OpenAPI Spec in JSON</a><br> <a href=\"/api-yaml\">OpenAPI Spec in YAML</a><br>  ### Offboarding Every service conntected to Grünes Netz needs to remove users when they are removed from `saml.gruene.de`. Connected services need to pull a list of users waiting for removal at least once a week. api.gruene.de needs to be informed whether the user did not exist or was removed. API tokens can be obtained from `technik@verdigado.com`.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Verdigado\GrueneApiClient\apis;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Verdigado\GrueneApiClient\ApiException;
use Verdigado\GrueneApiClient\Configuration;
use Verdigado\GrueneApiClient\HeaderSelector;
use Verdigado\GrueneApiClient\ObjectSerializer;

/**
 * DivisionsApi Class Doc Comment
 *
 * @category Class
 * @package  Verdigado\GrueneApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DivisionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'findDivisions' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation findDivisions
     *
     * Find divisions
     *
     * @param  float $limit limit (optional, default to 20)
     * @param  float $offset offset (optional)
     * @param  string $hierarchy Filter by hierarchy (optional)
     * @param  string $level Filter by hierarchy level (optional)
     * @param  string[] $division_key Filter by division keys (optional)
     * @param  string $search Search name attributes for substring (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findDivisions'] to see the possible values for this operation
     *
     * @throws \Verdigado\GrueneApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Verdigado\GrueneApiClient\models\FindDivisionsResponse
     */
    public function findDivisions($limit = 20, $offset = null, $hierarchy = null, $level = null, $division_key = null, $search = null, string $contentType = self::contentTypes['findDivisions'][0])
    {
        list($response) = $this->findDivisionsWithHttpInfo($limit, $offset, $hierarchy, $level, $division_key, $search, $contentType);
        return $response;
    }

    /**
     * Operation findDivisionsWithHttpInfo
     *
     * Find divisions
     *
     * @param  float $limit (optional, default to 20)
     * @param  float $offset (optional)
     * @param  string $hierarchy Filter by hierarchy (optional)
     * @param  string $level Filter by hierarchy level (optional)
     * @param  string[] $division_key Filter by division keys (optional)
     * @param  string $search Search name attributes for substring (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findDivisions'] to see the possible values for this operation
     *
     * @throws \Verdigado\GrueneApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Verdigado\GrueneApiClient\models\FindDivisionsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function findDivisionsWithHttpInfo($limit = 20, $offset = null, $hierarchy = null, $level = null, $division_key = null, $search = null, string $contentType = self::contentTypes['findDivisions'][0])
    {
        $request = $this->findDivisionsRequest($limit, $offset, $hierarchy, $level, $division_key, $search, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Verdigado\GrueneApiClient\models\FindDivisionsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Verdigado\GrueneApiClient\models\FindDivisionsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Verdigado\GrueneApiClient\models\FindDivisionsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Verdigado\GrueneApiClient\models\FindDivisionsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Verdigado\GrueneApiClient\models\FindDivisionsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findDivisionsAsync
     *
     * Find divisions
     *
     * @param  float $limit (optional, default to 20)
     * @param  float $offset (optional)
     * @param  string $hierarchy Filter by hierarchy (optional)
     * @param  string $level Filter by hierarchy level (optional)
     * @param  string[] $division_key Filter by division keys (optional)
     * @param  string $search Search name attributes for substring (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findDivisions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findDivisionsAsync($limit = 20, $offset = null, $hierarchy = null, $level = null, $division_key = null, $search = null, string $contentType = self::contentTypes['findDivisions'][0])
    {
        return $this->findDivisionsAsyncWithHttpInfo($limit, $offset, $hierarchy, $level, $division_key, $search, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findDivisionsAsyncWithHttpInfo
     *
     * Find divisions
     *
     * @param  float $limit (optional, default to 20)
     * @param  float $offset (optional)
     * @param  string $hierarchy Filter by hierarchy (optional)
     * @param  string $level Filter by hierarchy level (optional)
     * @param  string[] $division_key Filter by division keys (optional)
     * @param  string $search Search name attributes for substring (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findDivisions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findDivisionsAsyncWithHttpInfo($limit = 20, $offset = null, $hierarchy = null, $level = null, $division_key = null, $search = null, string $contentType = self::contentTypes['findDivisions'][0])
    {
        $returnType = '\Verdigado\GrueneApiClient\models\FindDivisionsResponse';
        $request = $this->findDivisionsRequest($limit, $offset, $hierarchy, $level, $division_key, $search, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findDivisions'
     *
     * @param  float $limit (optional, default to 20)
     * @param  float $offset (optional)
     * @param  string $hierarchy Filter by hierarchy (optional)
     * @param  string $level Filter by hierarchy level (optional)
     * @param  string[] $division_key Filter by division keys (optional)
     * @param  string $search Search name attributes for substring (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findDivisions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function findDivisionsRequest($limit = 20, $offset = null, $hierarchy = null, $level = null, $division_key = null, $search = null, string $contentType = self::contentTypes['findDivisions'][0])
    {

        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling DivisionsApi.findDivisions, must be bigger than or equal to 1.');
        }
        
        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling DivisionsApi.findDivisions, must be bigger than or equal to 0.');
        }
        





        $resourcePath = '/v1/divisions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $hierarchy,
            'hierarchy', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $level,
            'level', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $division_key,
            'division_key', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search,
            'search', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
