<?php
/**
 * NbApiApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Verdigado\GrueneApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gruene API
 *
 * ## OpenAPI Endpoints <a href=\"/api-json\">OpenAPI Spec in JSON</a><br> <a href=\"/api-yaml\">OpenAPI Spec in YAML</a><br>  ### Offboarding Every service conntected to Grünes Netz needs to remove users when they are removed from `saml.gruene.de`. Connected services need to pull a list of users waiting for removal at least once a week. api.gruene.de needs to be informed whether the user did not exist or was removed. API tokens can be obtained from `technik@verdigado.com`.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Verdigado\GrueneApiClient\apis;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Verdigado\GrueneApiClient\ApiException;
use Verdigado\GrueneApiClient\Configuration;
use Verdigado\GrueneApiClient\HeaderSelector;
use Verdigado\GrueneApiClient\ObjectSerializer;

/**
 * NbApiApi Class Doc Comment
 *
 * @category Class
 * @package  Verdigado\GrueneApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NbApiApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'findGroups' => [
            'application/json',
        ],
        'findOrganizations' => [
            'application/json',
        ],
        'findRegionalChapters' => [
            'application/json',
        ],
        'getRegionalChapter' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation findGroups
     *
     * Find all groups
     *
     * @param  string $filter_external_refs_type Filter by external reference type (optional)
     * @param  string $filter_external_refs_key Filter by external reference ID (sherpa role id) (optional)
     * @param  string $filter_level Filter by role level (optional)
     * @param  string $filter_type Filter by role type (optional)
     * @param  string $filter_slug Filter by role slug (optional)
     * @param  string $filter_active Filter by active status. True by default (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findGroups'] to see the possible values for this operation
     *
     * @throws \Verdigado\GrueneApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Verdigado\GrueneApiClient\models\FindNbGroupsResponse
     */
    public function findGroups($filter_external_refs_type = null, $filter_external_refs_key = null, $filter_level = null, $filter_type = null, $filter_slug = null, $filter_active = null, string $contentType = self::contentTypes['findGroups'][0])
    {
        list($response) = $this->findGroupsWithHttpInfo($filter_external_refs_type, $filter_external_refs_key, $filter_level, $filter_type, $filter_slug, $filter_active, $contentType);
        return $response;
    }

    /**
     * Operation findGroupsWithHttpInfo
     *
     * Find all groups
     *
     * @param  string $filter_external_refs_type Filter by external reference type (optional)
     * @param  string $filter_external_refs_key Filter by external reference ID (sherpa role id) (optional)
     * @param  string $filter_level Filter by role level (optional)
     * @param  string $filter_type Filter by role type (optional)
     * @param  string $filter_slug Filter by role slug (optional)
     * @param  string $filter_active Filter by active status. True by default (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findGroups'] to see the possible values for this operation
     *
     * @throws \Verdigado\GrueneApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Verdigado\GrueneApiClient\models\FindNbGroupsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function findGroupsWithHttpInfo($filter_external_refs_type = null, $filter_external_refs_key = null, $filter_level = null, $filter_type = null, $filter_slug = null, $filter_active = null, string $contentType = self::contentTypes['findGroups'][0])
    {
        $request = $this->findGroupsRequest($filter_external_refs_type, $filter_external_refs_key, $filter_level, $filter_type, $filter_slug, $filter_active, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Verdigado\GrueneApiClient\models\FindNbGroupsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Verdigado\GrueneApiClient\models\FindNbGroupsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Verdigado\GrueneApiClient\models\FindNbGroupsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Verdigado\GrueneApiClient\models\FindNbGroupsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Verdigado\GrueneApiClient\models\FindNbGroupsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findGroupsAsync
     *
     * Find all groups
     *
     * @param  string $filter_external_refs_type Filter by external reference type (optional)
     * @param  string $filter_external_refs_key Filter by external reference ID (sherpa role id) (optional)
     * @param  string $filter_level Filter by role level (optional)
     * @param  string $filter_type Filter by role type (optional)
     * @param  string $filter_slug Filter by role slug (optional)
     * @param  string $filter_active Filter by active status. True by default (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findGroups'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findGroupsAsync($filter_external_refs_type = null, $filter_external_refs_key = null, $filter_level = null, $filter_type = null, $filter_slug = null, $filter_active = null, string $contentType = self::contentTypes['findGroups'][0])
    {
        return $this->findGroupsAsyncWithHttpInfo($filter_external_refs_type, $filter_external_refs_key, $filter_level, $filter_type, $filter_slug, $filter_active, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findGroupsAsyncWithHttpInfo
     *
     * Find all groups
     *
     * @param  string $filter_external_refs_type Filter by external reference type (optional)
     * @param  string $filter_external_refs_key Filter by external reference ID (sherpa role id) (optional)
     * @param  string $filter_level Filter by role level (optional)
     * @param  string $filter_type Filter by role type (optional)
     * @param  string $filter_slug Filter by role slug (optional)
     * @param  string $filter_active Filter by active status. True by default (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findGroups'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findGroupsAsyncWithHttpInfo($filter_external_refs_type = null, $filter_external_refs_key = null, $filter_level = null, $filter_type = null, $filter_slug = null, $filter_active = null, string $contentType = self::contentTypes['findGroups'][0])
    {
        $returnType = '\Verdigado\GrueneApiClient\models\FindNbGroupsResponse';
        $request = $this->findGroupsRequest($filter_external_refs_type, $filter_external_refs_key, $filter_level, $filter_type, $filter_slug, $filter_active, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findGroups'
     *
     * @param  string $filter_external_refs_type Filter by external reference type (optional)
     * @param  string $filter_external_refs_key Filter by external reference ID (sherpa role id) (optional)
     * @param  string $filter_level Filter by role level (optional)
     * @param  string $filter_type Filter by role type (optional)
     * @param  string $filter_slug Filter by role slug (optional)
     * @param  string $filter_active Filter by active status. True by default (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findGroups'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function findGroupsRequest($filter_external_refs_type = null, $filter_external_refs_key = null, $filter_level = null, $filter_type = null, $filter_slug = null, $filter_active = null, string $contentType = self::contentTypes['findGroups'][0])
    {








        $resourcePath = '/v1/party/groups';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_external_refs_type,
            'filter[external_refs.type]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_external_refs_key,
            'filter[external_refs.key]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_level,
            'filter[level]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_type,
            'filter[type]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_slug,
            'filter[slug]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_active,
            'filter[active]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }
        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation findOrganizations
     *
     * Find all organizations
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findOrganizations'] to see the possible values for this operation
     *
     * @throws \Verdigado\GrueneApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Verdigado\GrueneApiClient\models\FindNbOrganizationsResponse
     */
    public function findOrganizations(string $contentType = self::contentTypes['findOrganizations'][0])
    {
        list($response) = $this->findOrganizationsWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation findOrganizationsWithHttpInfo
     *
     * Find all organizations
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findOrganizations'] to see the possible values for this operation
     *
     * @throws \Verdigado\GrueneApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Verdigado\GrueneApiClient\models\FindNbOrganizationsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function findOrganizationsWithHttpInfo(string $contentType = self::contentTypes['findOrganizations'][0])
    {
        $request = $this->findOrganizationsRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Verdigado\GrueneApiClient\models\FindNbOrganizationsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Verdigado\GrueneApiClient\models\FindNbOrganizationsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Verdigado\GrueneApiClient\models\FindNbOrganizationsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Verdigado\GrueneApiClient\models\FindNbOrganizationsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Verdigado\GrueneApiClient\models\FindNbOrganizationsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findOrganizationsAsync
     *
     * Find all organizations
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findOrganizations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findOrganizationsAsync(string $contentType = self::contentTypes['findOrganizations'][0])
    {
        return $this->findOrganizationsAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findOrganizationsAsyncWithHttpInfo
     *
     * Find all organizations
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findOrganizations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findOrganizationsAsyncWithHttpInfo(string $contentType = self::contentTypes['findOrganizations'][0])
    {
        $returnType = '\Verdigado\GrueneApiClient\models\FindNbOrganizationsResponse';
        $request = $this->findOrganizationsRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findOrganizations'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findOrganizations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function findOrganizationsRequest(string $contentType = self::contentTypes['findOrganizations'][0])
    {


        $resourcePath = '/v1/party/organizations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }
        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation findRegionalChapters
     *
     * Find all regional chapters
     *
     * @param  float $limit Page limit (optional)
     * @param  float $offset Page offset (optional)
     * @param  string $filter_query Filter by query (optional)
     * @param  string $filter_id_prefix Filter by ID prefix (optional)
     * @param  string $filter_type Filter by type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findRegionalChapters'] to see the possible values for this operation
     *
     * @throws \Verdigado\GrueneApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Verdigado\GrueneApiClient\models\FindNbRegionalChaptersResponse
     */
    public function findRegionalChapters($limit = null, $offset = null, $filter_query = null, $filter_id_prefix = null, $filter_type = null, string $contentType = self::contentTypes['findRegionalChapters'][0])
    {
        list($response) = $this->findRegionalChaptersWithHttpInfo($limit, $offset, $filter_query, $filter_id_prefix, $filter_type, $contentType);
        return $response;
    }

    /**
     * Operation findRegionalChaptersWithHttpInfo
     *
     * Find all regional chapters
     *
     * @param  float $limit Page limit (optional)
     * @param  float $offset Page offset (optional)
     * @param  string $filter_query Filter by query (optional)
     * @param  string $filter_id_prefix Filter by ID prefix (optional)
     * @param  string $filter_type Filter by type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findRegionalChapters'] to see the possible values for this operation
     *
     * @throws \Verdigado\GrueneApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Verdigado\GrueneApiClient\models\FindNbRegionalChaptersResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function findRegionalChaptersWithHttpInfo($limit = null, $offset = null, $filter_query = null, $filter_id_prefix = null, $filter_type = null, string $contentType = self::contentTypes['findRegionalChapters'][0])
    {
        $request = $this->findRegionalChaptersRequest($limit, $offset, $filter_query, $filter_id_prefix, $filter_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Verdigado\GrueneApiClient\models\FindNbRegionalChaptersResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Verdigado\GrueneApiClient\models\FindNbRegionalChaptersResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Verdigado\GrueneApiClient\models\FindNbRegionalChaptersResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Verdigado\GrueneApiClient\models\FindNbRegionalChaptersResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Verdigado\GrueneApiClient\models\FindNbRegionalChaptersResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findRegionalChaptersAsync
     *
     * Find all regional chapters
     *
     * @param  float $limit Page limit (optional)
     * @param  float $offset Page offset (optional)
     * @param  string $filter_query Filter by query (optional)
     * @param  string $filter_id_prefix Filter by ID prefix (optional)
     * @param  string $filter_type Filter by type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findRegionalChapters'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findRegionalChaptersAsync($limit = null, $offset = null, $filter_query = null, $filter_id_prefix = null, $filter_type = null, string $contentType = self::contentTypes['findRegionalChapters'][0])
    {
        return $this->findRegionalChaptersAsyncWithHttpInfo($limit, $offset, $filter_query, $filter_id_prefix, $filter_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findRegionalChaptersAsyncWithHttpInfo
     *
     * Find all regional chapters
     *
     * @param  float $limit Page limit (optional)
     * @param  float $offset Page offset (optional)
     * @param  string $filter_query Filter by query (optional)
     * @param  string $filter_id_prefix Filter by ID prefix (optional)
     * @param  string $filter_type Filter by type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findRegionalChapters'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findRegionalChaptersAsyncWithHttpInfo($limit = null, $offset = null, $filter_query = null, $filter_id_prefix = null, $filter_type = null, string $contentType = self::contentTypes['findRegionalChapters'][0])
    {
        $returnType = '\Verdigado\GrueneApiClient\models\FindNbRegionalChaptersResponse';
        $request = $this->findRegionalChaptersRequest($limit, $offset, $filter_query, $filter_id_prefix, $filter_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findRegionalChapters'
     *
     * @param  float $limit Page limit (optional)
     * @param  float $offset Page offset (optional)
     * @param  string $filter_query Filter by query (optional)
     * @param  string $filter_id_prefix Filter by ID prefix (optional)
     * @param  string $filter_type Filter by type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findRegionalChapters'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function findRegionalChaptersRequest($limit = null, $offset = null, $filter_query = null, $filter_id_prefix = null, $filter_type = null, string $contentType = self::contentTypes['findRegionalChapters'][0])
    {

        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling NbApiApi.findRegionalChapters, must be bigger than or equal to 1.');
        }
        
        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling NbApiApi.findRegionalChapters, must be bigger than or equal to 0.');
        }
        

        if ($filter_id_prefix !== null && strlen($filter_id_prefix) > 8) {
            throw new \InvalidArgumentException('invalid length for "$filter_id_prefix" when calling NbApiApi.findRegionalChapters, must be smaller than or equal to 8.');
        }
        


        $resourcePath = '/v1/party/regionalchapters';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_query,
            'filter[query]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_id_prefix,
            'filter[id_prefix]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_type,
            'filter[type]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }
        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getRegionalChapter
     *
     * Get regional chapter by division key
     *
     * @param  string $division_key division_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRegionalChapter'] to see the possible values for this operation
     *
     * @throws \Verdigado\GrueneApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Verdigado\GrueneApiClient\models\NbRegionalChapterDto
     */
    public function getRegionalChapter($division_key, string $contentType = self::contentTypes['getRegionalChapter'][0])
    {
        list($response) = $this->getRegionalChapterWithHttpInfo($division_key, $contentType);
        return $response;
    }

    /**
     * Operation getRegionalChapterWithHttpInfo
     *
     * Get regional chapter by division key
     *
     * @param  string $division_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRegionalChapter'] to see the possible values for this operation
     *
     * @throws \Verdigado\GrueneApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Verdigado\GrueneApiClient\models\NbRegionalChapterDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRegionalChapterWithHttpInfo($division_key, string $contentType = self::contentTypes['getRegionalChapter'][0])
    {
        $request = $this->getRegionalChapterRequest($division_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Verdigado\GrueneApiClient\models\NbRegionalChapterDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Verdigado\GrueneApiClient\models\NbRegionalChapterDto' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Verdigado\GrueneApiClient\models\NbRegionalChapterDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Verdigado\GrueneApiClient\models\NbRegionalChapterDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Verdigado\GrueneApiClient\models\NbRegionalChapterDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getRegionalChapterAsync
     *
     * Get regional chapter by division key
     *
     * @param  string $division_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRegionalChapter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRegionalChapterAsync($division_key, string $contentType = self::contentTypes['getRegionalChapter'][0])
    {
        return $this->getRegionalChapterAsyncWithHttpInfo($division_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getRegionalChapterAsyncWithHttpInfo
     *
     * Get regional chapter by division key
     *
     * @param  string $division_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRegionalChapter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRegionalChapterAsyncWithHttpInfo($division_key, string $contentType = self::contentTypes['getRegionalChapter'][0])
    {
        $returnType = '\Verdigado\GrueneApiClient\models\NbRegionalChapterDto';
        $request = $this->getRegionalChapterRequest($division_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getRegionalChapter'
     *
     * @param  string $division_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRegionalChapter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRegionalChapterRequest($division_key, string $contentType = self::contentTypes['getRegionalChapter'][0])
    {

        // verify the required parameter 'division_key' is set
        if ($division_key === null || (is_array($division_key) && count($division_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $division_key when calling getRegionalChapter'
            );
        }


        $resourcePath = '/v1/party/regionalchapters/{divisionKey}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($division_key !== null) {
            $resourcePath = str_replace(
                '{' . 'divisionKey' . '}',
                ObjectSerializer::toPathValue($division_key),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }
        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
